### ISSUE TITLE
[Event] Fiery Fallout (Common)

### ISSUE THREAD

**Issue by ben-lear** [AsdarDevelops/PokeRogue-Events#88]
### Event Name

Fiery Fallout

### Rarity Tier

Common

### Waves

41-179

### Description

Player encounters a seriously bad fire storm on top of the mountain. 

ART NEED:
Fire storm effect of some kind? Maybe just heatwave.

If the player presses onward, they will find a courting male and female Volcarona.

### Biomes

VOLCANO

### Options offered to the player

- [ ] Search for the Source
    - _Starts a battle against a male + female Volcarona_
    - _Player cannot switch out at start of the fight (it's an "ambush")_
    - _Sets Sunny Day weather at the start of the fight_
    - _Both Volcarona get free Quiver Dance at start of fight_
    - _Both of player's pokemon are hit by fire spin at the start of the fight_
    - _Charcoal guaranteed in rewards screen_
- [ ] Tough it Out
    - _Sets Sunny Day weather_
    - _All non-Fire types in party take 30% damage_
    - _1 random non-Fire type in party is burned_
- [ ] Get help from your Fire types
    - _At least 2 fire types required for this option_
    - _Your fire type pokemon easily lead you to the Volcarona_
    - _They are able to calm them down without a combat_
    - _They earn participant exp as if they had defeated the Volcarona_
    - _Charcoal guaranteed in rewards screen_

### Explanation/Notes on Design

Gives the player access to Charcoal, and rewards the right Challenge team.

**Comment by AsdarDevelops** [comment]
Some things:

- If this doesn't have a pairing anymore, I think it's fine to bump it to higher wave to match Volcarona's levelling. Underlevel early-evolved Volcarona exists in the game as a static encounter so up to you. Just saying that since we no longer have the mirroring, you can add the wave that you wanted initially.

- "Tough is out" is pretty brutal atm, dealing more damage than "Lost at Sea" and applying status. I think 20% + 2 burns would be a nice "around the same power level, but different" approach. It also has no reward or exp.

- Option 3 should still give Charcoal on top of the reward, like Option 1 and 2 would do.

Other than that seems good to me, can't wait to get my ass handed by these two.

**Comment by AsdarDevelops** [comment]
Removing Art Request label
